// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meszukzjwqagpyzvvqpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lc3p1a3pqd3FhZ3B5enZ2cXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTE0MDAsImV4cCI6MjA2MjM4NzQwMH0.I37vwhjWkGEl0eqnXddM0UgKFzM-muUkrOJ19O3xm1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);